[build]
  command = "hugo --gc --minify --buildFuture -b $URL"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.147.9"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true

# Form handling configuration
[[redirects]]
  from = "/subscribe-success"
  to = "/thank-you"
  status = 301

# Handle form submissions
[[headers]]
  for = "/thank-you"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
